add a11y configuration for title
instructure/mediaelement pull request #14
Opened 2017-01-27 22:17 UTC by evilvillage

Add capability to customize title text for a11y.

2017-01-27 23:42 UTC, benternet requested changes

2017-01-27 23:42 UTC, benternet commented on src/js/mep-player.js
> +					videoPlayerTitle = t.options.titleText;
do we need a spec that the title can be set?

2017-02-17 08:40 UTC, zellv commented on src/js/mep-player.js
> +					videoPlayerTitle = t.options.titleText;
Don't think so.

2017-02-21 20:23 UTC, mziwisky commented
@evilvillage please rebase

2017-02-22 22:01 UTC, mziwisky requested changes
can you revert all those whitespace changes?

2017-02-22 22:46 UTC, mziwisky approved these changes
+2

2017-02-22 22:58 UTC, merged