Size time slider only based on visible controls
instructure/mediaelement pull request #31
Opened 2017-06-09 19:35 UTC by tennety

The calculation for sizing the time slider includes a check for whether
the last control in the list wrapped to the next line if the slider was
too long, and to reduce the slider size incrementally till that was no
longer the case. If the last control is set to `display: none`, this
calculation becomes unpredictable and in some cases continues till the
slider is 1px wide.

Hidden controls shouldn’t be affecting the slider size.

2017-06-12 23:10 UTC, benternet requested changes

2017-06-12 23:10 UTC, benternet commented on src/js/mep-player.js
> +				others = rail.siblings().filter(':visible'), // don't include `display: none` controls when sizing
i think this is already taken care of by line 1166, yea?

2017-06-13 14:24 UTC, tennety commented on src/js/mep-player.js
> +				others = rail.siblings().filter(':visible'), // don't include `display: none` controls when sizing
Good catch, but the issue is actually on the next line, 1144, where `lastControl` is set to `others.last()`. In our case, this is not a visible element, and throws off the calculations which try to reduce the rail size. Maybe I can change that line to something like `lastControl = others.filter(':visible').last()` instead to make the fix clearer.

2017-06-13 19:26 UTC, benternet commented on src/js/mep-player.js
> +				others = rail.siblings().filter(':visible'), // don't include `display: none` controls when sizing
Let's go this way
> I can take out the visible check on line 1166, because nothing is gained by including invisible elements anyway.

2017-06-13 19:48 UTC, benternet approved these changes

2017-06-19 17:28 UTC, kyler-instructure commented
QA +1

2017-06-20 13:43 UTC, merged