add default functions for jump forward/back
instructure/mediaelement pull request #34
Opened 2017-07-07 20:17 UTC by simonista

2017-07-10 19:37 UTC, benternet commented
@simonista we have a history of updating the build files in the PR that contains the src file changes as well. mind updating with those?

2017-07-10 19:42 UTC, mziwisky requested changes
Nice catch, just asking for a little more in the code comments

2017-07-10 19:42 UTC, mziwisky commented on src/js/mep-player.js
> +		// default amount to move forward when forward key is pressed
this comment should differentiate the option from that of `defaultSeekForwardInterval`, and `defaultJumpBackwardInterval` should have a corresponding comment

2017-07-10 19:43 UTC, a-b-r-o-w-n requested changes
The code looks good. Could you update the commit message to include 'interval'? The message now makes it seem like the functions that were added were for jumping, not for the interval.

2017-07-10 20:11 UTC, simonista commented
@benternet / @mziwisky / @astephenb : done

2017-07-10 20:20 UTC, mziwisky requested changes

2017-07-10 20:20 UTC, mziwisky commented on build/mediaelement-and-player.js
> +    // default amount to move back when Page Down key is pressed
copy-pasta fail -- s/back/forward.  (also s/  /\t/g)

2017-07-10 20:22 UTC, simonista commented on build/mediaelement-and-player.js
> +    // default amount to move back when Page Down key is pressed
🤦‍♂️ thanks

2017-07-10 20:23 UTC, mziwisky approved these changes
👍

2017-07-14 17:51 UTC, simonista commented
@astephenb could you re-review this to unblock it?

2017-07-14 17:52 UTC, a-b-r-o-w-n approved these changes

2017-07-17 15:39 UTC, simonista commented
@benternet any chance we could merge this today, and then I can re-build generated files for the other PR?

2017-07-18 04:06 UTC, benternet commented
ah sorry @simonista didn't see this earlier today. we typically have the author merge upon review complete and QA complete. do you happen to have QA resources that would test this or should we wait on Arc QA resources? our QA team is pretty slammed ATM but i'll check with them (@kyler-instructure) tomorrow.

2017-07-19 18:57 UTC, simonista commented
Hey @benternet, I could show my team's QA person locally that without this there were console errors and with it there aren't. Since it's just adding to default config, I'm not sure how valuable regression testing is.  What do you think @kyler-instructure, what would you like to see here?

2017-08-01 23:57 UTC, kyler-instructure approved these changes
QA +1

2017-08-03 16:19 UTC, merged