Arc 3188
instructure/mediaelement pull request #43
Opened 2018-04-17 23:27 UTC by kelpycreek

Reading directly from target.buffered creates a race condition where its value can change if the user is clicking backwards through the video a lot. This should resolve that.

2018-04-17 23:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/mediaelement?pullRequest=43) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/mediaelement?pullRequest=43) before we can accept your contribution.<br/><hr/>**Forrest Keppler** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/mediaelement?pullRequest=43) it.</sub>

2018-04-18 21:26 UTC, mziwisky requested changes
don't forget to build the package (`grunt html5only`) and add the built assets to the commit

2018-04-18 21:26 UTC, mziwisky commented on src/js/mep-feature-progress.js
> +				//reading target.buffered can lead to race conditions
i think this comment is hard to make sense of out of the context of this diff.  it looks like you're saying something can lead to race conditions, and then you're doing that thing anyway.  so for a comment, i think something like "target.buffered can change in the middle of this execution thread, so we must store a reference to it to make sure we're dealing with the exact same object below" is more descriptive

but really, i'd just omit the comment altogether.  race condition or not, it's a nicer style anyway to peel off that property and make line 253 more succinct, so it doesn't really need justification with a comment.

2018-04-18 21:26 UTC, mziwisky commented on src/js/mep-feature-progress.js
>  			if (target && target.buffered && target.buffered.length > 0 && target.buffered.end && target.duration) {
actually, we should peel buffer off of target even before this conditional

2018-04-25 19:03 UTC, mziwisky requested changes

2018-04-25 19:03 UTC, mziwisky commented on src/js/mep-feature-progress.js
> +			if (buffer && target.buffered.length > 0 && target.buffered.end && target.duration) {
still referencing `target.buffered` a couple of times here.  should just deal with the `buffer` reference instead

2018-04-25 21:01 UTC, mziwisky approved these changes
good stuff

2018-04-26 20:16 UTC, bensolo-inst commented
Looks good.  No issues observed.  Tested in:  Chrome, Firefox, Safari, and Edge   (Though SauceLabs performance in Edge was very poor today / difficult to test well in local env.)

2018-04-27 18:04 UTC, merged